### ISSUE TITLE
pdf-explore issue

### ISSUE THREAD

**Issue by martinlindhe** [micahflee/pdf-redact-tools#6]
$ ./pdf-explode ~/e-books/First\ Aid\ Made\ Easy.pdf 
Converting PDF to PNGs
convert.im6: unable to open image `/home/ml/e-books/First Aid Made Easy_pages//home/ml/e-books/First Aid Made Easy-transparent-0.png': No such file or directory @ error/blob.c/OpenBlob/2638.
convert.im6: WriteBlob Failed `/home/ml/e-books/First Aid Made Easy_pages//home/ml/e-books/First Aid Made Easy-transparent-0.png' @ error/png.c/MagickPNGErrorHandler/1728.
Flattening PNGs
Traceback (most recent call last):
  File "./pdf-explode", line 55, in <module>
    filename_template = pages_dirname+'/'+filenames[0].replace('-0.png', '-{0}.png')
IndexError: list index out of range

**Comment by micahflee** [comment]
fixed!
