### ISSUE TITLE
PDF-merged (redacted files) still contain meta-data from PDFTk (PDF Toolkit)

### ISSUE THREAD

**Issue by Wikinaut** [micahflee/pdf-redact-tools#9]
After pdf-merging, the readacted pdf still contains the information from the merge process, which reveals information from the pdftk merge process. 

I think, a postprocess should remove this information, and should perhaps also manipulate the date/time information, or replace it by something meaningful or meaningless....

Meta-data (*File > Properties*) as shown by Acrobat Reader (two examples from different installations):
<img src="https://i.imgur.com/u6acbp8.png">

**Comment by micahflee** [comment]
Just confirmed that the latest version no longer includes this metadata.

**Comment by Wikinaut** [comment]
confirmed! thanks
